Repository ComicScrip/lyon-react-mars22-p2g4, pull requests merged in 2022-04, with the labels that each got.

#3 install react router dom
  img/logo_meteo.png
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/index.css
  src/index.js
  src/logo.svg
  src/screens/About.js
  src/screens/Home.js
  src/screens/Journal.js
  src/screens/LiveView.js
  src/screens/Road.js
  src/screens/Summary.js
Labels: Ready for validation

#35 Contact form
  package-lock.json
  package.json
  src/components/ContactForm.js
  src/components/ContactForm.module.css
  src/components/DevMember.js
  src/components/DevMember.module.css
  src/components/assets/Inter-Bold.ttf
  src/components/assets/Inter-Regular.ttf
  src/components/assets/aboutBackground.jpg
  src/components/assets/dev1.jpg
  src/components/assets/dev2.jpg
  src/components/assets/dev3.jpg
  src/components/assets/dev4.jpg
  src/components/assets/dev5.jpg
  src/index.css
  src/screens/About.js
  src/screens/About.module.css
Labels: Ready for prod, Changes requested

#36 Home
  package-lock.json
  src/components/assets/home-background.png
  src/screens/Home.js
  src/screens/Home.module.css
Labels: Ready for prod

#45 Liveview
  package-lock.json
  package.json
  postcss.config.js
  public/curseur.png
  public/index.html
  src/App.js
  src/components/DisplayMapLive.js
  src/components/Header.js
  src/components/Main.js
  src/components/RunInformations/ControlButtons/ControlButtons.css
  src/components/RunInformations/ControlButtons/ControlButtons.js
  src/components/RunInformations/RunInformations.css
  src/components/RunInformations/RunInformations.js
  src/components/RunInformations/Timer/Timer.css
  src/components/RunInformations/Timer/Timer.js
  src/index.css
  src/screens/LiveView.js
Labels: Fixed - ready for prod

#48 Navbar
  .husky/pre-commit
  img/logo_meteo.png
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/meteo.png
  public/rezo.jpg
  public/shoe.svg
  src/App.css
  src/App.js
  src/App.test.js
  src/components/ContactForm.js
  src/components/ContactForm.module.css
  src/components/DevMember.js
  src/components/DevMember.module.css
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/Main.js
  src/components/assets/Inter-Bold.ttf
  src/components/assets/Inter-Regular.ttf
  src/components/assets/aboutBackground.jpg
  src/components/assets/dev1.jpg
  src/components/assets/dev2.jpg
  src/components/assets/dev3.jpg
  src/components/assets/dev4.jpg
  src/components/assets/dev5.jpg
  src/index.css
  src/index.js
  src/logo.svg
  src/screens/About.js
  src/screens/About.module.css
  src/screens/Home.js
  src/screens/Journal.js
  src/screens/LiveView.js
  src/screens/Road.js
  src/screens/Summary.js
Labels: Ready for validation, Changes requested

#42 Result page
  package-lock.json
  package.json
  src/components/InformationsRace.js
  src/components/Photos.css
  src/components/SummaryRaceInfos.js
  src/components/assets/backgroundRecapRace.png
  src/reportWebVitals.js
  src/screens/Summary.css
  src/screens/Summary.js
  src/setupTests.js
Labels: Fixed - ready for prod

#54 Home
  package-lock.json
  public/index.html
  public/logo192.png
  public/meteo.png
  public/rezo.jpg
  public/shoe.svg
  src/App.css
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/index.css
  src/screens/About.module.css
  src/screens/Home.module.css
Labels: Ready for prod

#43 Meteo
  .env sample
  .eslintrc.json
  package-lock.json
  src/components/CurrentMeteo.js
  src/components/CurrentMeteoIcon.js
  src/components/Footer.css
  src/components/Header.css
  src/components/Header.js
  src/components/MeteoForecast.js
  src/components/MeteoForecastIcon.js
  src/components/MeteoTemp.js
  src/icons/01d.png
  src/icons/01n.png
  src/icons/02d.png
  src/icons/02n.png
  src/icons/03d.png
  src/icons/03n.png
  src/icons/04d.png
  src/icons/04n.png
  src/icons/09d.png
  src/icons/09n.png
  src/icons/10d.png
  src/icons/10n.png
  src/icons/11d.png
  src/icons/11n.png
  src/icons/13d.png
  src/icons/13n.png
  src/icons/50d.png
  src/icons/50n.png
  src/icons/unknown.png
  src/screens/Home.js
Labels: Ready for prod
