Repository ComicScrip/lyon-react-mars22-p2g4, pull requests merged in 2022-05, with the labels that each got.

#40 Display maps
  .env sample
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/DisplayMap.js
  src/components/Footer.css
  src/components/Main.js
  src/components/MeteoForecast.js
  src/components/MeteoForecastIcon.js
  src/components/MeteoTemp.js
  src/components/PathCard.js
  src/components/Photos.css
  src/components/Photos.js
  src/components/RunInformations/ControlButtons/ControlButtons.js
  src/index.css
  src/ressources/pathExample.json
  src/screens/LiveView.js
  src/screens/PathDetails.css
  src/screens/PathDetails.js
  src/screens/Paths.css
  src/screens/Paths.js
  src/screens/Resume.js
  src/screens/Summary.js
Labels: Fixed - ready for prod

#67 Live view design
  public/curseur.png
  src/components/DisplayMapLive.js
  src/components/RunInformations/ControlButtons/ControlButtons.css
  src/components/RunInformations/ControlButtons/ControlButtons.js
  src/components/RunInformations/RunInformations.js
  src/screens/LiveView.js
Labels: Ready for prod

#69 Supp
  src/components/DevMember.module.css
  src/components/Footer.css
  src/components/Main.js
  src/components/assets/400cat.jpg
  src/screens/About.module.css
  src/screens/Home.module.css
  src/screens/NotFoundPage.js
  src/screens/NotFoundPage.module.css
  src/screens/PathDetails.js
Labels: Ready for validation

#65 Restart path
  public/run_bg.jpg
  src/components/ChangeMapCenter.js
  src/components/DisplayMap.js
  src/components/DisplayMapLive.js
  src/components/FinishedPaths.js
  src/components/Header.css
  src/components/Header.js
  src/components/JournalCard.js
  src/components/Main.js
  src/components/PathCard.js
  src/components/Photos.js
  src/components/Photos.module.css
  src/components/PredefinedPaths.js
  src/components/RunInformations/RunInformations.js
  src/components/SummaryButtons.js
  src/components/SummaryButtons.module.css
  src/components/SummaryRaceInfos.js
  src/components/SummaryRaceInfos.module.css
  src/ressources/donePathObject.js
  src/ressources/hikking_sample_lyon.json
  src/ressources/lyon_touristic.json
  src/ressources/pathExample.json
  src/ressources/test.json
  src/screens/Journal.css
  src/screens/Journal.js
  src/screens/LiveView.js
  src/screens/PathDetails.css
  src/screens/PathDetails.js
  src/screens/Paths.css
  src/screens/Paths.js
  src/screens/Summary.css
  src/screens/Summary.js
  src/screens/Summary.module.css
Labels: Ready for prod

#72 do some css change
  src/components/Header.css
  src/components/Header.js
  src/screens/PathDetails.css
  src/screens/PathDetails.js
  src/screens/Paths.css
Labels: Ready for prod

#74 Corrections
  public/manifest.json
  src/components/Footer.js
  src/components/Header.js
  src/components/InformationsRace.js
  src/components/MeteoForecastIcon.js
  src/components/MeteoTemp.js
  src/components/Photos.js
  src/components/RunInformations/ControlButtons/ControlButtons.css
  src/components/RunInformations/Timer/Timer.css
  src/screens/Journal.js
  src/screens/LiveView.js
  src/screens/PathDetails.js
Labels: Ready for prod
